uid: 01ke4yxxb48pfac4zqd9c55eep
name: schede
isConcrete: true
parentSchemaUid: 01ke4yx5m0h4p51ekxxqdrh8cb
workspaceUid: 01ke4ywah3mkv7mhz3gxef80rk
definition:
  description: schede
  attributes:
    -
      id: Key
      name: Key
      type: string
      required: true
      unique: true
      system: true
      editable: false
      description: "Unique system-generated identifier"
    -
      id: Name
      name: Name
      type: string
      required: true
      system: true
      editable: true
      description: Object name
    -
      id: Created
      name: Created
      type: datetime
      required: true
      system: true
      editable: false
      description: Creation timestamp
    -
      id: Updated
      name: Updated
      type: datetime
      required: true
      system: true
      editable: false
      description: Last update timestamp
    -
      id: 01ke4yydzdgh16019jw3yfbafx
      name: typo
      key: typo
      type: enum
      required: true
      unique: false
      indexed: false
      default: ""
      description: ""
      multiValue: true
      readOnly: false
      visible: true
      order: 0
      cardinalityMin: 1
      cardinalityMax: 10
      options:
        - GPU
        - Video
        - Suono
    -
      id: 01ke4z184nb7m2zypcx2xv09xm
      name: text address
      key: text_address
      type: string
      required: false
      unique: false
      indexed: false
      default: FFFFFF
      description: text address
      multiValue: true
      readOnly: false
      visible: true
      order: 1
      cardinalityMin: 1
      cardinalityMax: 10
      constraints:
        regex: "[A-F0-9]+"
    -
      id: 01ke4z34t6kxzc77m8eahtg0h2
      name: intaddresses
      key: intaddresses
      type: integer
      required: false
      unique: false
      indexed: false
      default: 1
      description: ""
      multiValue: true
      readOnly: false
      visible: true
      order: 2
      cardinalityMin: 1
      cardinalityMax: 10
      constraints:
        min: 0
        max: 90
  iconCode: 58178
  iconSource: system
  globalProperties:
createdAt: "2026-01-04T17:54:57.636972"
updatedAt: "2026-01-05T03:05:46.742189"
