{
  "uid": "01kjr7tsdb742r5zpr1vsf4jv7",
  "name": "LNF ELI NP",
  "description": null,
  "parentSchemaUid": null,
  "isConcrete": true,
  "attributes": [],
  "metadata": {
    "createdAt": null,
    "updatedAt": null,
    "version": null
  }
}