{
  "uid": "01kjmv6ndwdhp37p2e7623kaxc",
  "name": "Magnet",
  "description": null,
  "parentSchemaUid": "01kjmv6r6vq5tv7vmd30vr3x41",
  "isConcrete": true,
  "attributes": [
    {
      "key": "key",
      "name": "Key",
      "type": "string",
      "required": true,
      "description": "Unique system-generated identifier",
      "defaultValue": null,
      "options": null
    },
    {
      "key": "name",
      "name": "Name",
      "type": "string",
      "required": true,
      "description": "Object name",
      "defaultValue": null,
      "options": null
    },
    {
      "key": "created",
      "name": "Created",
      "type": "datetime",
      "required": true,
      "description": "Creation timestamp",
      "defaultValue": null,
      "options": null
    },
    {
      "key": "updated",
      "name": "Updated",
      "type": "datetime",
      "required": true,
      "description": "Last update timestamp",
      "defaultValue": null,
      "options": null
    },
    {
      "key": "status",
      "name": "Status",
      "type": "status",
      "required": false,
      "description": "Asset lifecycle status",
      "defaultValue": null,
      "options": null
    },
    {
      "key": "alias",
      "name": "Alias",
      "type": "string",
      "required": false,
      "description": "Alternative name",
      "defaultValue": null,
      "options": null
    },
    {
      "key": "description",
      "name": "Description",
      "type": "text",
      "required": false,
      "description": "Description",
      "defaultValue": null,
      "options": null
    },
    {
      "key": "location",
      "name": "Location",
      "type": "reference",
      "required": false,
      "description": "Location",
      "defaultValue": null,
      "options": null
    },
    {
      "key": "serial",
      "name": "Serial",
      "type": "string",
      "required": false,
      "description": "ELI Serial ",
      "defaultValue": null,
      "options": null
    },
    {
      "key": "rack",
      "name": "Rack",
      "type": "reference",
      "required": false,
      "description": "Rack",
      "defaultValue": null,
      "options": null
    },
    {
      "key": "connector",
      "name": "connector",
      "type": "reference",
      "required": false,
      "description": "Cable connector",
      "defaultValue": null,
      "options": null
    },
    {
      "key": "layout",
      "name": "Layout",
      "type": "reference",
      "required": false,
      "description": "Layout Position",
      "defaultValue": null,
      "options": null
    },
    {
      "key": "module",
      "name": "Module",
      "type": "string",
      "required": false,
      "description": "Module Name",
      "defaultValue": null,
      "options": null
    },
    {
      "key": "cavo",
      "name": "Cavo",
      "type": "reference",
      "required": false,
      "description": "numero inventario",
      "defaultValue": null,
      "options": null
    },
    {
      "key": "type",
      "name": "Type",
      "type": "enum",
      "required": false,
      "description": "Magnet Type",
      "defaultValue": null,
      "options": [
        "QUAD",
        "DIP",
        "HCOR",
        "VCOR",
        "UND",
        "SOL",
        "SXT",
        "QUA"
      ]
    },
    {
      "key": "voltage",
      "name": "Voltage",
      "type": "string",
      "required": false,
      "description": "Nominal Magnet Voltage",
      "defaultValue": null,
      "options": null
    },
    {
      "key": "current",
      "name": "Current",
      "type": "string",
      "required": false,
      "description": "Nominal Magnet Current",
      "defaultValue": null,
      "options": null
    },
    {
      "key": "inlet_temp",
      "name": "Inlet Temp",
      "type": "string",
      "required": false,
      "description": "Demin. Cooling Water Inlet Temp. (°C)",
      "defaultValue": null,
      "options": null
    },
    {
      "key": "rise_temp",
      "name": "Rise Temp",
      "type": "string",
      "required": false,
      "description": "Demin. Cooling Water Temp. Rise      (°C)",
      "defaultValue": null,
      "options": null
    },
    {
      "key": "water_pressure_drop",
      "name": "Water Pressure Drop",
      "type": "string",
      "required": false,
      "description": "Demin. Cooling Water Pressure drop      (bar)",
      "defaultValue": null,
      "options": null
    },
    {
      "key": "water_coling_flow",
      "name": "Water Coling Flow",
      "type": "string",
      "required": false,
      "description": "Demin. Cooling Water Flow      (l/min)",
      "defaultValue": null,
      "options": null
    },
    {
      "key": "weight",
      "name": "Weight",
      "type": "string",
      "required": false,
      "description": "Weight (kg)",
      "defaultValue": null,
      "options": null
    },
    {
      "key": "crosssection",
      "name": "CrossSection",
      "type": "string",
      "required": false,
      "description": "Cross Section",
      "defaultValue": null,
      "options": null
    },
    {
      "key": "currentin",
      "name": "CurrentIn",
      "type": "string",
      "required": false,
      "description": "Current In",
      "defaultValue": null,
      "options": null
    },
    {
      "key": "powersupply",
      "name": "Powersupply",
      "type": "reference",
      "required": false,
      "description": "Power Supply ",
      "defaultValue": null,
      "options": null
    },
    {
      "key": "power",
      "name": "Power",
      "type": "string",
      "required": false,
      "description": "Nominal Magnet Power (kW)",
      "defaultValue": null,
      "options": null
    }
  ],
  "metadata": {
    "createdAt": null,
    "updatedAt": null,
    "version": null
  }
}