{
  "uid": "01kjmv6m5nkmb2c8s7gr96v8m6",
  "name": "LNF ELI NP",
  "description": null,
  "parentSchemaUid": null,
  "isConcrete": true,
  "attributes": [],
  "metadata": {
    "createdAt": null,
    "updatedAt": null,
    "version": null
  }
}